= Чат клиент-сървър

Да се разработи чат клиент-сървър със следната функционалност:
-	Да обслужва много потребители едновременно.
-	Всеки потребител има уникално име и парола с което се аутентицира пред системата. Данните за потребителите да се пазят във файл. 
-	Потребителите могат да напуснат системата по всяко време.
-	Да могат да се изпращат лични съобщение до друг активен (регистриран и в момента свързан към сървъра) потребител.
-	Комуникации чрез чат-стаи
	-	Създаване и изтриване на чат-стая. Изтриването да е възможно само от потребителя създал стаята.
	-	Влизане и напускане на чат-стая
	-	Показване на всички чат стаи
	-	Извеждане на всички активни потребители в дадена чат стая
	-	Изпращане на съобщение към всички в чат стаята. 
-	Запазване на история на комуникацията в чат стаи във файл. 
	-	При влизане в стая да се покаже историята на изпратените съобщения до момента (ако има такива)
-	Потребителите да могат да трансферират файлове помежду си
	-	Изпращащият посочва до кога иска да изпрати файл и къде се намира файлът
	-	Получаващият получава нотификация, че някой се опитва да му изпрати файл и има възможност да приеме/откаже файла. Ако приеме файла, трябва да посочи къде да го съхрани.