= Чат клиент-сървър

== Да се разработи чат клиент-сървър със следната функционалност:
 - Да обслужва много потребители едновременно.
 - Всеки потребител има уникално име и парола с което се аутентицира пред системата. Данните за потребителите да се пазят във файл. 
 - Потребителите могат да напуснат системата по всяко време.
 - Да могат да се изпращат лични съобщение до друг активен (регистриран и в момента свързан към сървъра) потребител.
 - Комуникации чрез чат-стаи:
  1. Създаване и изтриване на чат-стая. Изтриването да е възможно само от потребителя създал стаята.
  2. Влизане и напускане на чат-стая.
  3. Показване на всички чат стаи.
  4. Извеждане на всички активни потребители в дадена чат стая.
  5. Изпращане на съобщение към всички в чат стаята. 
 - Запазване на история на комуникацията в чат стаи във файл. 
  1. При влизане в стая да се покаже историята на изпратените съобщения до момента (ако има такива)
 - Потребителите да могат да трансферират файлове помежду си
  1. Изпращащият посочва до кога иска да изпрати файл и къде се намира файлът
  2. Получаващият получава нотификация, че някой се опитва да му изпрати файл и има възможност да приеме/откаже файла. Ако приеме файла, трябва да посочи къде да го съхрани.

== Примерни клиентски команди:
asd:
---
connect <host> <port> - свързва се към сървъра
register <username> <password> - регистрира потребител
login <username> <password> - влиза в системата
disconnect – напуска системата
list-users – извежда списък със всички активни в момента потребители

send <username> <message> - изпраща лично съобщение до даден потребител.
send-file <username> <file_location> - изпраща файл до потребител.

create-room <room_name> - създава нова стая
delete-room <room_name> - изтрива съществуваща стая
join-room <room_name> - присъединява се към стая
leave-room <room_name> - напуска стая
list-rooms - извежда всички активни стаи (с поне 1 активен потребител)
list-users <room> - извежда списък със всички активни потребители в дадена стая
---
